chore: bump dependencies (#79)
* deps: yaml@2.1.1->2.2.2, yargs@17.5.1->17.7.1

* deps: which@2.0.1->3.0.0

* deps: semver@7.3.7->7.5.0

* devDeps: eslint@8.27.0->8.39.0

* deps: semver@7.3.7->7.5.0, lru-cache@7.12.0->7.18.3

* deps: pony-cause@2.1.0->2.1.9

* deps: glob@8.0.3->10.2.2

* deps: execa@5.0.0->7.1.1

* deps: @metamask/utils@3.6.0->5.0.2

* devDeps: @lavamoat/allow-scripts@2.0.3->2.3.1

* devDeps: jest@29.3.0->29.5.0

* devDeps: rimraf@3.0.2->4.0.5

* tsconfig: set skipLibCheck = true

unblocks error:

node_modules/path-scurry/node_modules/lru-cache/dist/cjs/index.d.ts:244:15 - error TS2430: Interface 'FetchOptionsNoContext<K, V, FC>' incorrectly extends interface 'FetchOptions<K, V, FC>'.
  Types of property 'context' are incompatible.
    Type 'undefined' is not assignable to type 'FC'.
      'FC' could be instantiated with an arbitrary type which could be unrelated to 'undefined'.

244     interface FetchOptionsNoContext<K, V, FC> extends FetchOptions<K, V, FC> {
                  ~~~~~~~~~~~~~~~~~~~~~

Found 1 error in node_modules/path-scurry/node_modules/lru-cache/dist/cjs/index.d.ts:244

* test: update changed screen-scraped cli output